image_output_path: '/home/aesk/baykara_ws/myData/IMG/'
csv_dir: '/home/aesk/baykara_ws/myData/'
csv_name: 'driving_log.csv'
bagfile_name: 'sag5' 
camera_topic: '/camera'
CanBus_topic: '/CanBusData'
add_or_new: 'add'